#! /bin/bash

set -x
set -euo pipefail

app_dir=${1:-/Applications}
vivaldiApp="$app_dir/Vivaldi.app"

wd=$(dirname "$0")

vivaldiResources="$vivaldiApp"/'Contents/Frameworks/Vivaldi Framework.framework/Resources/vivaldi'

for i in "$wd"/mods/*.{js,html}; do
    b=$(basename "$i")
    if ! diff -u "$vivaldiResources/$b" "$i"; then
        cp "$i" "$vivaldiResources/$b"
    fi
done
